"""Add name field to User

Revision ID: 20a43787e686
Revises: a064fc6d91f1
Create Date: 2026-08-01 10:11:25.663300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a43787e686'
down_revision = 'a064fc6d91f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
     batch_op.add_column(sa.Column('name', sa.String(), nullable=True))   

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
