"""Add acreage to listings

Revision ID: af6ae5349816
Revises: 20a43787e686
Create Date: 2026-08-04 01:32:29.048307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6ae5349816'
down_revision = '20a43787e686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acreage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_per_kg', sa.Float(), nullable=True))
        batch_op.drop_column('tree_count')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_kg', sa.Float(), nullable=True))
        batch_op.drop_column('weight_recorded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_recorded', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('quantity_kg')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tree_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('price_per_kg')
        batch_op.drop_column('acreage')

    # ### end Alembic commands ###
